ALTER TABLE [dbo].[EventAttendeePreferenceValues]
    ADD CONSTRAINT [PK_EventAttendeePreferenceValues] PRIMARY KEY NONCLUSTERED ([EventAttendees_Id] ASC, [PreferenceValues_Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

