ALTER TABLE [dbo].[EventOrganizer]
    ADD CONSTRAINT [PK_EventOrganizer] PRIMARY KEY NONCLUSTERED ([EventsAsOrganizer_Id] ASC, [Organizers_Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

