ALTER TABLE [dbo].[PresentationSpeakers]
    ADD CONSTRAINT [PK_PresentationSpeakers] PRIMARY KEY NONCLUSTERED ([PresentationsAsSpeaker_Id] ASC, [Speakers_Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

