ALTER TABLE [dbo].[SponsorPerson]
    ADD CONSTRAINT [PK_SponsorPerson] PRIMARY KEY NONCLUSTERED ([SponsorsAsOwner_Id] ASC, [Owners_Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

