ALTER TABLE [dbo].[TrackOwner]
    ADD CONSTRAINT [PK_TrackOwner] PRIMARY KEY NONCLUSTERED ([TracksAsOwner_Id] ASC, [Owners_Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

