//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace CodeCamp.WP7.AgendaServiceRef {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgendaItem", Namespace="http://tempuri.org/")]
    public partial class AgendaItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int SessionIdField;
        
        private string RatingField;
        
        private string CommentField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((this.SessionIdField.Equals(value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((object.ReferenceEquals(this.RatingField, value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://tempuri.org/")]
    public partial class Event : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string EmailField;
        
        private string PasswordField;
        
        private System.Collections.ObjectModel.ObservableCollection<CodeCamp.WP7.AgendaServiceRef.Track> TracksField;
        
        private System.Collections.ObjectModel.ObservableCollection<CodeCamp.WP7.AgendaServiceRef.Speaker> SpeakersField;
        
        private System.Collections.ObjectModel.ObservableCollection<CodeCamp.WP7.AgendaServiceRef.Session> SessionsField;
        
        private System.Collections.ObjectModel.ObservableCollection<CodeCamp.WP7.AgendaServiceRef.AgendaItem> AgendaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<CodeCamp.WP7.AgendaServiceRef.Track> Tracks {
            get {
                return this.TracksField;
            }
            set {
                if ((object.ReferenceEquals(this.TracksField, value) != true)) {
                    this.TracksField = value;
                    this.RaisePropertyChanged("Tracks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Collections.ObjectModel.ObservableCollection<CodeCamp.WP7.AgendaServiceRef.Speaker> Speakers {
            get {
                return this.SpeakersField;
            }
            set {
                if ((object.ReferenceEquals(this.SpeakersField, value) != true)) {
                    this.SpeakersField = value;
                    this.RaisePropertyChanged("Speakers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Collections.ObjectModel.ObservableCollection<CodeCamp.WP7.AgendaServiceRef.Session> Sessions {
            get {
                return this.SessionsField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionsField, value) != true)) {
                    this.SessionsField = value;
                    this.RaisePropertyChanged("Sessions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public System.Collections.ObjectModel.ObservableCollection<CodeCamp.WP7.AgendaServiceRef.AgendaItem> Agenda {
            get {
                return this.AgendaField;
            }
            set {
                if ((object.ReferenceEquals(this.AgendaField, value) != true)) {
                    this.AgendaField = value;
                    this.RaisePropertyChanged("Agenda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Track", Namespace="http://tempuri.org/")]
    public partial class Track : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Speaker", Namespace="http://tempuri.org/")]
    public partial class Speaker : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string NameField;
        
        private string TitleField;
        
        private string TwitterField;
        
        private string BlogField;
        
        private string BioField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Twitter {
            get {
                return this.TwitterField;
            }
            set {
                if ((object.ReferenceEquals(this.TwitterField, value) != true)) {
                    this.TwitterField = value;
                    this.RaisePropertyChanged("Twitter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Blog {
            get {
                return this.BlogField;
            }
            set {
                if ((object.ReferenceEquals(this.BlogField, value) != true)) {
                    this.BlogField = value;
                    this.RaisePropertyChanged("Blog");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Bio {
            get {
                return this.BioField;
            }
            set {
                if ((object.ReferenceEquals(this.BioField, value) != true)) {
                    this.BioField = value;
                    this.RaisePropertyChanged("Bio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Session", Namespace="http://tempuri.org/")]
    public partial class Session : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private string NameField;
        
        private string TrackField;
        
        private string DescriptionField;
        
        private string LevelField;
        
        private string StartTimeField;
        
        private string EndTimeField;
        
        private string SpeakerField;
        
        private string RoomField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Track {
            get {
                return this.TrackField;
            }
            set {
                if ((object.ReferenceEquals(this.TrackField, value) != true)) {
                    this.TrackField = value;
                    this.RaisePropertyChanged("Track");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Level {
            get {
                return this.LevelField;
            }
            set {
                if ((object.ReferenceEquals(this.LevelField, value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.StartTimeField, value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.EndTimeField, value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Speaker {
            get {
                return this.SpeakerField;
            }
            set {
                if ((object.ReferenceEquals(this.SpeakerField, value) != true)) {
                    this.SpeakerField = value;
                    this.RaisePropertyChanged("Speaker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Room {
            get {
                return this.RoomField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomField, value) != true)) {
                    this.RoomField = value;
                    this.RaisePropertyChanged("Room");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AgendaServiceRef.AgendaServiceSoap")]
    public interface AgendaServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetAgendaItems", ReplyAction="*")]
        System.IAsyncResult BeginGetAgendaItems(CodeCamp.WP7.AgendaServiceRef.GetAgendaItemsRequest request, System.AsyncCallback callback, object asyncState);
        
        CodeCamp.WP7.AgendaServiceRef.GetAgendaItemsResponse EndGetAgendaItems(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/UpdateRating", ReplyAction="*")]
        System.IAsyncResult BeginUpdateRating(CodeCamp.WP7.AgendaServiceRef.UpdateRatingRequest request, System.AsyncCallback callback, object asyncState);
        
        CodeCamp.WP7.AgendaServiceRef.UpdateRatingResponse EndUpdateRating(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Attend", ReplyAction="*")]
        System.IAsyncResult BeginAttend(CodeCamp.WP7.AgendaServiceRef.AttendRequest request, System.AsyncCallback callback, object asyncState);
        
        CodeCamp.WP7.AgendaServiceRef.AttendResponse EndAttend(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetEvent", ReplyAction="*")]
        System.IAsyncResult BeginGetEvent(CodeCamp.WP7.AgendaServiceRef.GetEventRequest request, System.AsyncCallback callback, object asyncState);
        
        CodeCamp.WP7.AgendaServiceRef.GetEventResponse EndGetEvent(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAgendaItemsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAgendaItems", Namespace="http://tempuri.org/", Order=0)]
        public CodeCamp.WP7.AgendaServiceRef.GetAgendaItemsRequestBody Body;
        
        public GetAgendaItemsRequest() {
        }
        
        public GetAgendaItemsRequest(CodeCamp.WP7.AgendaServiceRef.GetAgendaItemsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAgendaItemsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetAgendaItemsRequestBody() {
        }
        
        public GetAgendaItemsRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAgendaItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAgendaItemsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CodeCamp.WP7.AgendaServiceRef.GetAgendaItemsResponseBody Body;
        
        public GetAgendaItemsResponse() {
        }
        
        public GetAgendaItemsResponse(CodeCamp.WP7.AgendaServiceRef.GetAgendaItemsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAgendaItemsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<CodeCamp.WP7.AgendaServiceRef.AgendaItem> GetAgendaItemsResult;
        
        public GetAgendaItemsResponseBody() {
        }
        
        public GetAgendaItemsResponseBody(System.Collections.ObjectModel.ObservableCollection<CodeCamp.WP7.AgendaServiceRef.AgendaItem> GetAgendaItemsResult) {
            this.GetAgendaItemsResult = GetAgendaItemsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRatingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRating", Namespace="http://tempuri.org/", Order=0)]
        public CodeCamp.WP7.AgendaServiceRef.UpdateRatingRequestBody Body;
        
        public UpdateRatingRequest() {
        }
        
        public UpdateRatingRequest(CodeCamp.WP7.AgendaServiceRef.UpdateRatingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRatingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CodeCamp.WP7.AgendaServiceRef.AgendaItem item;
        
        public UpdateRatingRequestBody() {
        }
        
        public UpdateRatingRequestBody(string email, string password, CodeCamp.WP7.AgendaServiceRef.AgendaItem item) {
            this.email = email;
            this.password = password;
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRatingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRatingResponse", Namespace="http://tempuri.org/", Order=0)]
        public CodeCamp.WP7.AgendaServiceRef.UpdateRatingResponseBody Body;
        
        public UpdateRatingResponse() {
        }
        
        public UpdateRatingResponse(CodeCamp.WP7.AgendaServiceRef.UpdateRatingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateRatingResponseBody {
        
        public UpdateRatingResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AttendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Attend", Namespace="http://tempuri.org/", Order=0)]
        public CodeCamp.WP7.AgendaServiceRef.AttendRequestBody Body;
        
        public AttendRequest() {
        }
        
        public AttendRequest(CodeCamp.WP7.AgendaServiceRef.AttendRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AttendRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int sessionId;
        
        public AttendRequestBody() {
        }
        
        public AttendRequestBody(string email, string password, int sessionId) {
            this.email = email;
            this.password = password;
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AttendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AttendResponse", Namespace="http://tempuri.org/", Order=0)]
        public CodeCamp.WP7.AgendaServiceRef.AttendResponseBody Body;
        
        public AttendResponse() {
        }
        
        public AttendResponse(CodeCamp.WP7.AgendaServiceRef.AttendResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AttendResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<CodeCamp.WP7.AgendaServiceRef.AgendaItem> AttendResult;
        
        public AttendResponseBody() {
        }
        
        public AttendResponseBody(System.Collections.ObjectModel.ObservableCollection<CodeCamp.WP7.AgendaServiceRef.AgendaItem> AttendResult) {
            this.AttendResult = AttendResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEventRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEvent", Namespace="http://tempuri.org/", Order=0)]
        public CodeCamp.WP7.AgendaServiceRef.GetEventRequestBody Body;
        
        public GetEventRequest() {
        }
        
        public GetEventRequest(CodeCamp.WP7.AgendaServiceRef.GetEventRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEventRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetEventRequestBody() {
        }
        
        public GetEventRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEventResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEventResponse", Namespace="http://tempuri.org/", Order=0)]
        public CodeCamp.WP7.AgendaServiceRef.GetEventResponseBody Body;
        
        public GetEventResponse() {
        }
        
        public GetEventResponse(CodeCamp.WP7.AgendaServiceRef.GetEventResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEventResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CodeCamp.WP7.AgendaServiceRef.Event GetEventResult;
        
        public GetEventResponseBody() {
        }
        
        public GetEventResponseBody(CodeCamp.WP7.AgendaServiceRef.Event GetEventResult) {
            this.GetEventResult = GetEventResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AgendaServiceSoapChannel : CodeCamp.WP7.AgendaServiceRef.AgendaServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAgendaItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAgendaItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CodeCamp.WP7.AgendaServiceRef.GetAgendaItemsResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CodeCamp.WP7.AgendaServiceRef.GetAgendaItemsResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateRatingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateRatingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CodeCamp.WP7.AgendaServiceRef.UpdateRatingResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CodeCamp.WP7.AgendaServiceRef.UpdateRatingResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AttendCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AttendCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CodeCamp.WP7.AgendaServiceRef.AttendResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CodeCamp.WP7.AgendaServiceRef.AttendResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CodeCamp.WP7.AgendaServiceRef.GetEventResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CodeCamp.WP7.AgendaServiceRef.GetEventResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgendaServiceSoapClient : System.ServiceModel.ClientBase<CodeCamp.WP7.AgendaServiceRef.AgendaServiceSoap>, CodeCamp.WP7.AgendaServiceRef.AgendaServiceSoap {
        
        private BeginOperationDelegate onBeginGetAgendaItemsDelegate;
        
        private EndOperationDelegate onEndGetAgendaItemsDelegate;
        
        private System.Threading.SendOrPostCallback onGetAgendaItemsCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateRatingDelegate;
        
        private EndOperationDelegate onEndUpdateRatingDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateRatingCompletedDelegate;
        
        private BeginOperationDelegate onBeginAttendDelegate;
        
        private EndOperationDelegate onEndAttendDelegate;
        
        private System.Threading.SendOrPostCallback onAttendCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetEventDelegate;
        
        private EndOperationDelegate onEndGetEventDelegate;
        
        private System.Threading.SendOrPostCallback onGetEventCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public AgendaServiceSoapClient() {
        }
        
        public AgendaServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgendaServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgendaServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgendaServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetAgendaItemsCompletedEventArgs> GetAgendaItemsCompleted;
        
        public event System.EventHandler<UpdateRatingCompletedEventArgs> UpdateRatingCompleted;
        
        public event System.EventHandler<AttendCompletedEventArgs> AttendCompleted;
        
        public event System.EventHandler<GetEventCompletedEventArgs> GetEventCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CodeCamp.WP7.AgendaServiceRef.AgendaServiceSoap.BeginGetAgendaItems(CodeCamp.WP7.AgendaServiceRef.GetAgendaItemsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAgendaItems(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CodeCamp.WP7.AgendaServiceRef.GetAgendaItemsResponse CodeCamp.WP7.AgendaServiceRef.AgendaServiceSoap.EndGetAgendaItems(System.IAsyncResult result) {
            return base.Channel.EndGetAgendaItems(result);
        }
        
        private System.IAsyncResult OnBeginGetAgendaItems(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CodeCamp.WP7.AgendaServiceRef.GetAgendaItemsRequest request = ((CodeCamp.WP7.AgendaServiceRef.GetAgendaItemsRequest)(inValues[0]));
            return ((CodeCamp.WP7.AgendaServiceRef.AgendaServiceSoap)(this)).BeginGetAgendaItems(request, callback, asyncState);
        }
        
        private object[] OnEndGetAgendaItems(System.IAsyncResult result) {
            CodeCamp.WP7.AgendaServiceRef.GetAgendaItemsResponse retVal = ((CodeCamp.WP7.AgendaServiceRef.AgendaServiceSoap)(this)).EndGetAgendaItems(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAgendaItemsCompleted(object state) {
            if ((this.GetAgendaItemsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAgendaItemsCompleted(this, new GetAgendaItemsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAgendaItemsAsync(CodeCamp.WP7.AgendaServiceRef.GetAgendaItemsRequest request) {
            this.GetAgendaItemsAsync(request, null);
        }
        
        public void GetAgendaItemsAsync(CodeCamp.WP7.AgendaServiceRef.GetAgendaItemsRequest request, object userState) {
            if ((this.onBeginGetAgendaItemsDelegate == null)) {
                this.onBeginGetAgendaItemsDelegate = new BeginOperationDelegate(this.OnBeginGetAgendaItems);
            }
            if ((this.onEndGetAgendaItemsDelegate == null)) {
                this.onEndGetAgendaItemsDelegate = new EndOperationDelegate(this.OnEndGetAgendaItems);
            }
            if ((this.onGetAgendaItemsCompletedDelegate == null)) {
                this.onGetAgendaItemsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAgendaItemsCompleted);
            }
            base.InvokeAsync(this.onBeginGetAgendaItemsDelegate, new object[] {
                        request}, this.onEndGetAgendaItemsDelegate, this.onGetAgendaItemsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CodeCamp.WP7.AgendaServiceRef.AgendaServiceSoap.BeginUpdateRating(CodeCamp.WP7.AgendaServiceRef.UpdateRatingRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateRating(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CodeCamp.WP7.AgendaServiceRef.UpdateRatingResponse CodeCamp.WP7.AgendaServiceRef.AgendaServiceSoap.EndUpdateRating(System.IAsyncResult result) {
            return base.Channel.EndUpdateRating(result);
        }
        
        private System.IAsyncResult OnBeginUpdateRating(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CodeCamp.WP7.AgendaServiceRef.UpdateRatingRequest request = ((CodeCamp.WP7.AgendaServiceRef.UpdateRatingRequest)(inValues[0]));
            return ((CodeCamp.WP7.AgendaServiceRef.AgendaServiceSoap)(this)).BeginUpdateRating(request, callback, asyncState);
        }
        
        private object[] OnEndUpdateRating(System.IAsyncResult result) {
            CodeCamp.WP7.AgendaServiceRef.UpdateRatingResponse retVal = ((CodeCamp.WP7.AgendaServiceRef.AgendaServiceSoap)(this)).EndUpdateRating(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateRatingCompleted(object state) {
            if ((this.UpdateRatingCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateRatingCompleted(this, new UpdateRatingCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateRatingAsync(CodeCamp.WP7.AgendaServiceRef.UpdateRatingRequest request) {
            this.UpdateRatingAsync(request, null);
        }
        
        public void UpdateRatingAsync(CodeCamp.WP7.AgendaServiceRef.UpdateRatingRequest request, object userState) {
            if ((this.onBeginUpdateRatingDelegate == null)) {
                this.onBeginUpdateRatingDelegate = new BeginOperationDelegate(this.OnBeginUpdateRating);
            }
            if ((this.onEndUpdateRatingDelegate == null)) {
                this.onEndUpdateRatingDelegate = new EndOperationDelegate(this.OnEndUpdateRating);
            }
            if ((this.onUpdateRatingCompletedDelegate == null)) {
                this.onUpdateRatingCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateRatingCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateRatingDelegate, new object[] {
                        request}, this.onEndUpdateRatingDelegate, this.onUpdateRatingCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CodeCamp.WP7.AgendaServiceRef.AgendaServiceSoap.BeginAttend(CodeCamp.WP7.AgendaServiceRef.AttendRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAttend(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CodeCamp.WP7.AgendaServiceRef.AttendResponse CodeCamp.WP7.AgendaServiceRef.AgendaServiceSoap.EndAttend(System.IAsyncResult result) {
            return base.Channel.EndAttend(result);
        }
        
        private System.IAsyncResult OnBeginAttend(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CodeCamp.WP7.AgendaServiceRef.AttendRequest request = ((CodeCamp.WP7.AgendaServiceRef.AttendRequest)(inValues[0]));
            return ((CodeCamp.WP7.AgendaServiceRef.AgendaServiceSoap)(this)).BeginAttend(request, callback, asyncState);
        }
        
        private object[] OnEndAttend(System.IAsyncResult result) {
            CodeCamp.WP7.AgendaServiceRef.AttendResponse retVal = ((CodeCamp.WP7.AgendaServiceRef.AgendaServiceSoap)(this)).EndAttend(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAttendCompleted(object state) {
            if ((this.AttendCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AttendCompleted(this, new AttendCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AttendAsync(CodeCamp.WP7.AgendaServiceRef.AttendRequest request) {
            this.AttendAsync(request, null);
        }
        
        public void AttendAsync(CodeCamp.WP7.AgendaServiceRef.AttendRequest request, object userState) {
            if ((this.onBeginAttendDelegate == null)) {
                this.onBeginAttendDelegate = new BeginOperationDelegate(this.OnBeginAttend);
            }
            if ((this.onEndAttendDelegate == null)) {
                this.onEndAttendDelegate = new EndOperationDelegate(this.OnEndAttend);
            }
            if ((this.onAttendCompletedDelegate == null)) {
                this.onAttendCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAttendCompleted);
            }
            base.InvokeAsync(this.onBeginAttendDelegate, new object[] {
                        request}, this.onEndAttendDelegate, this.onAttendCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CodeCamp.WP7.AgendaServiceRef.AgendaServiceSoap.BeginGetEvent(CodeCamp.WP7.AgendaServiceRef.GetEventRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetEvent(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CodeCamp.WP7.AgendaServiceRef.GetEventResponse CodeCamp.WP7.AgendaServiceRef.AgendaServiceSoap.EndGetEvent(System.IAsyncResult result) {
            return base.Channel.EndGetEvent(result);
        }
        
        private System.IAsyncResult OnBeginGetEvent(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CodeCamp.WP7.AgendaServiceRef.GetEventRequest request = ((CodeCamp.WP7.AgendaServiceRef.GetEventRequest)(inValues[0]));
            return ((CodeCamp.WP7.AgendaServiceRef.AgendaServiceSoap)(this)).BeginGetEvent(request, callback, asyncState);
        }
        
        private object[] OnEndGetEvent(System.IAsyncResult result) {
            CodeCamp.WP7.AgendaServiceRef.GetEventResponse retVal = ((CodeCamp.WP7.AgendaServiceRef.AgendaServiceSoap)(this)).EndGetEvent(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetEventCompleted(object state) {
            if ((this.GetEventCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetEventCompleted(this, new GetEventCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetEventAsync(CodeCamp.WP7.AgendaServiceRef.GetEventRequest request) {
            this.GetEventAsync(request, null);
        }
        
        public void GetEventAsync(CodeCamp.WP7.AgendaServiceRef.GetEventRequest request, object userState) {
            if ((this.onBeginGetEventDelegate == null)) {
                this.onBeginGetEventDelegate = new BeginOperationDelegate(this.OnBeginGetEvent);
            }
            if ((this.onEndGetEventDelegate == null)) {
                this.onEndGetEventDelegate = new EndOperationDelegate(this.OnEndGetEvent);
            }
            if ((this.onGetEventCompletedDelegate == null)) {
                this.onGetEventCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetEventCompleted);
            }
            base.InvokeAsync(this.onBeginGetEventDelegate, new object[] {
                        request}, this.onEndGetEventDelegate, this.onGetEventCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override CodeCamp.WP7.AgendaServiceRef.AgendaServiceSoap CreateChannel() {
            return new AgendaServiceSoapClientChannel(this);
        }
        
        private class AgendaServiceSoapClientChannel : ChannelBase<CodeCamp.WP7.AgendaServiceRef.AgendaServiceSoap>, CodeCamp.WP7.AgendaServiceRef.AgendaServiceSoap {
            
            public AgendaServiceSoapClientChannel(System.ServiceModel.ClientBase<CodeCamp.WP7.AgendaServiceRef.AgendaServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetAgendaItems(CodeCamp.WP7.AgendaServiceRef.GetAgendaItemsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetAgendaItems", _args, callback, asyncState);
                return _result;
            }
            
            public CodeCamp.WP7.AgendaServiceRef.GetAgendaItemsResponse EndGetAgendaItems(System.IAsyncResult result) {
                object[] _args = new object[0];
                CodeCamp.WP7.AgendaServiceRef.GetAgendaItemsResponse _result = ((CodeCamp.WP7.AgendaServiceRef.GetAgendaItemsResponse)(base.EndInvoke("GetAgendaItems", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateRating(CodeCamp.WP7.AgendaServiceRef.UpdateRatingRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("UpdateRating", _args, callback, asyncState);
                return _result;
            }
            
            public CodeCamp.WP7.AgendaServiceRef.UpdateRatingResponse EndUpdateRating(System.IAsyncResult result) {
                object[] _args = new object[0];
                CodeCamp.WP7.AgendaServiceRef.UpdateRatingResponse _result = ((CodeCamp.WP7.AgendaServiceRef.UpdateRatingResponse)(base.EndInvoke("UpdateRating", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAttend(CodeCamp.WP7.AgendaServiceRef.AttendRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Attend", _args, callback, asyncState);
                return _result;
            }
            
            public CodeCamp.WP7.AgendaServiceRef.AttendResponse EndAttend(System.IAsyncResult result) {
                object[] _args = new object[0];
                CodeCamp.WP7.AgendaServiceRef.AttendResponse _result = ((CodeCamp.WP7.AgendaServiceRef.AttendResponse)(base.EndInvoke("Attend", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetEvent(CodeCamp.WP7.AgendaServiceRef.GetEventRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetEvent", _args, callback, asyncState);
                return _result;
            }
            
            public CodeCamp.WP7.AgendaServiceRef.GetEventResponse EndGetEvent(System.IAsyncResult result) {
                object[] _args = new object[0];
                CodeCamp.WP7.AgendaServiceRef.GetEventResponse _result = ((CodeCamp.WP7.AgendaServiceRef.GetEventResponse)(base.EndInvoke("GetEvent", _args, result)));
                return _result;
            }
        }
    }
}
